### ISSUE TITLE
Par2 wrong 

### ISSUE THREAD

**Issue by EmanueleFrancazi** [scheidan/SiamSummerSchoolExercises#23]
in the R version (r_max = 10 instead of r_max = 5); also missing plot

**Comment by scheidan** [comment]
Can you please specify to where you refer? Thanks!

**Comment by abassi98** [comment]
I think it was in Solution/ExMonday/Section 2: Likelihood for Model Monod/Likelihood evaluation ... R code

**Comment by scheidan** [comment]
Thanks!
