### ISSUE TITLE
Problem Tuesday: missing Julia version in the problem formulation /hints

### ISSUE THREAD

**Issue by EmanueleFrancazi** [scheidan/SiamSummerSchoolExercises#26]
There is a full Julia implementation for the solutions but the hints/problem formulations miss this language version.

**Comment by scheidan** [comment]
In the section "Installation" on the [homepage](https://scheidan.github.io/SiamSummerSchoolExercises/)  we say to use the latest Stable Version (currently 1.9) . It also explains how to install the packages in the correct versions. 

[Here](https://scheidan.github.io/SiamSummerSchoolExercises/#version-info) we also show exact the versions used to compute the solutions (after the next update it will be julia 1.9 as well)

Do you think we should add something else?
